### PR TITLE
Updated activity events to show date

### PR DESCRIPTION
**Pull request by oliveiraigorm**

### CODE REVIEW

**Comment by mwalbeck** [comment]
Going from main to this pull request, the entries taken from the activity app disappear instead of date and time being added. Not really sure why, but that's the result I got when testing it.

**Comment by oliveiraigorm** [comment]
> Going from main to this pull request, the entries taken from the activity app disappear instead of date and time being added. Not really sure why, but that's the result I got when testing it.

That happened because the function inside filter on `utils.js` line 82 was not correct and wasn't filtering the events with the ✔️ created from the appointments app, and was giving back all the calendar activities

**Review by mwalbeck — APPROVED** [review]

**Comment by mwalbeck** [comment]
The formatting of the date and time probably needs to change, but we can pass that a long and then product can decide how exactly they want it to be display, but it does work now that I tested it properly.

**Comment by oliveiraigorm** [comment]
> The formatting of the date and time probably needs to change, but we can pass that a long and then product can decide how exactly they want it to be display, but it does work now that I tested it properly.

Yes definitely, João wasn't for a specific one for now, but the way it's implemented at the moment it can easily be customized.

**Pull request merged**
